name: Hello Workflow

on:
  push:
    branches: [main]

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "🎉 Hello from GitHub Actions!"



        name: Docker Build

on:
  push:
    branches: [ main ]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t my-app-image .

    - name: Run Docker container
      run: docker run -d -p 8080:8080 my-app-image

